# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.7-4-1.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Nvidia.CUDA
PackageVersion: 12.4.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://developer.download.nvidia.com/compute/cuda/12.4.1/local_installers/cuda_12.4.1_551.78_windows.exe
  InstallerSha256: 7D20C5EB186E4D3C64680FE5096BED05926AEA89754192102323C956C26244DE
ManifestType: installer
ManifestVersion: 1.6.0
